name: eng_llm_kb

services:

  minio:
    image: minio/minio:latest
    container_name: eng_rag_minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    ports:
      - "9005:9000"
      - "9006:9001"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  postgres-db:
    image: pgvector/pgvector:pg16
    container_name: eng_rag_postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # Langfuse expects its own DB, we can initialize others via scripts later or use one shared database.
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

  langfuse:
    image: langfuse/langfuse:2
    container_name: eng_rag_langfuse
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/postgres
      - NEXTAUTH_SECRET=my_super_secret_key_123
      - SALT=my_super_secure_salt_123
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=false
    ports:
      - "3000:3000"
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgvector_data:
